title: go-goog
repo: go-goog
version: v0.5
author:
  username: dvgamerr
  name: Kananek T.
  website: https://mr.touno.io/

description: >
  goog tool uses Google Photos API to continously download all photos on a local device.

# Build settings
cronitor_token: f79386d38615cb7705017b89c2652da1

# theme: dvgamerr/minima-lite
baseurl: /go-goog
remote_theme: dvgamerr/minima-lite

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%-d %b %Y"
  social_links:
    - { platform: devto,          user_url: "https://dev.to/dvgamerr" }
    - { platform: facebook,       user_url: "https://www.facebook.com/dvgamerr" }
    - { platform: x,        user_url: "https://x.com/dvgamerr" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCbMNge3pQHkb3avJvUj4hLA" }
